# Generated by Django 4.0.3 on 2022-03-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_funcionario_user'),
        ('documentos', '0002_documento_pertente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pertente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario'),
            preserve_default=False,
        ),
    ]
